# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraPotenciaSolar5.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1000, 760)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame = QtWidgets.QFrame(self.centralwidget)
        self.Frame.setGeometry(QtCore.QRect(0, 0, 1000, 700))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame.sizePolicy().hasHeightForWidth())
        self.Frame.setSizePolicy(sizePolicy)
        self.Frame.setMaximumSize(QtCore.QSize(1000, 700))
        self.Frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Frame.setObjectName("Frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Frame)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_52 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_52.sizePolicy().hasHeightForWidth())
        self.label_52.setSizePolicy(sizePolicy)
        self.label_52.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_9.addWidget(self.label_52)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(1)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.line_09HoraESTM = QtWidgets.QLineEdit(self.Frame)
        self.line_09HoraESTM.setMaxLength(5)
        self.line_09HoraESTM.setObjectName("line_09HoraESTM")
        self.gridLayout_6.addWidget(self.line_09HoraESTM, 0, 9, 1, 1)
        self.line_10HoraESTS = QtWidgets.QLineEdit(self.Frame)
        self.line_10HoraESTS.setMaxLength(5)
        self.line_10HoraESTS.setObjectName("line_10HoraESTS")
        self.gridLayout_6.addWidget(self.line_10HoraESTS, 0, 11, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.Frame)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.gridLayout_6.addWidget(self.label_77, 0, 10, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridLayout_6.addWidget(self.label_146, 0, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 1, 0, 1, 1)
        self.line_01Latitud = QtWidgets.QLineEdit(self.Frame)
        self.line_01Latitud.setMaxLength(5)
        self.line_01Latitud.setObjectName("line_01Latitud")
        self.gridLayout_6.addWidget(self.line_01Latitud, 0, 1, 1, 1)
        self.line_08HoraESTH = QtWidgets.QLineEdit(self.Frame)
        self.line_08HoraESTH.setMaxLength(5)
        self.line_08HoraESTH.setObjectName("line_08HoraESTH")
        self.gridLayout_6.addWidget(self.line_08HoraESTH, 0, 7, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.Frame)
        self.label_67.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.gridLayout_6.addWidget(self.label_67, 1, 11, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.Frame)
        self.label_66.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.gridLayout_6.addWidget(self.label_66, 1, 9, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.gridLayout_6.addWidget(self.label_151, 0, 6, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_148.setFont(font)
        self.label_148.setObjectName("label_148")
        self.gridLayout_6.addWidget(self.label_148, 0, 4, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.Frame)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.gridLayout_6.addWidget(self.label_79, 0, 8, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.Frame)
        self.label_65.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.gridLayout_6.addWidget(self.label_65, 1, 7, 1, 1)
        self.line_06Gh = QtWidgets.QLineEdit(self.Frame)
        self.line_06Gh.setMaxLength(5)
        self.line_06Gh.setObjectName("line_06Gh")
        self.gridLayout_6.addWidget(self.line_06Gh, 1, 5, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.gridLayout_6.addWidget(self.label_149, 1, 4, 1, 1)
        self.line_05Orientacion = QtWidgets.QLineEdit(self.Frame)
        self.line_05Orientacion.setMaxLength(5)
        self.line_05Orientacion.setObjectName("line_05Orientacion")
        self.gridLayout_6.addWidget(self.line_05Orientacion, 0, 5, 1, 1)
        self.line_02Longitud = QtWidgets.QLineEdit(self.Frame)
        self.line_02Longitud.setMaxLength(5)
        self.line_02Longitud.setObjectName("line_02Longitud")
        self.gridLayout_6.addWidget(self.line_02Longitud, 1, 1, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_147.setFont(font)
        self.label_147.setObjectName("label_147")
        self.gridLayout_6.addWidget(self.label_147, 2, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 3, 0, 1, 1)
        self.line_03HusoHorario = QtWidgets.QLineEdit(self.Frame)
        self.line_03HusoHorario.setMaxLength(5)
        self.line_03HusoHorario.setObjectName("line_03HusoHorario")
        self.gridLayout_6.addWidget(self.line_03HusoHorario, 2, 1, 1, 1)
        self.line_04Inclinacion = QtWidgets.QLineEdit(self.Frame)
        self.line_04Inclinacion.setMaxLength(5)
        self.line_04Inclinacion.setObjectName("line_04Inclinacion")
        self.gridLayout_6.addWidget(self.line_04Inclinacion, 3, 1, 1, 1)
        self.label_150 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.gridLayout_6.addWidget(self.label_150, 2, 4, 1, 1)
        self.line_07Albedo = QtWidgets.QLineEdit(self.Frame)
        self.line_07Albedo.setMaxLength(5)
        self.line_07Albedo.setObjectName("line_07Albedo")
        self.gridLayout_6.addWidget(self.line_07Albedo, 2, 5, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_152.setFont(font)
        self.label_152.setObjectName("label_152")
        self.gridLayout_6.addWidget(self.label_152, 2, 6, 1, 1)
        self.line_11FechaDia = QtWidgets.QLineEdit(self.Frame)
        self.line_11FechaDia.setMaxLength(5)
        self.line_11FechaDia.setObjectName("line_11FechaDia")
        self.gridLayout_6.addWidget(self.line_11FechaDia, 2, 7, 1, 1)
        self.line_12FechaMes = QtWidgets.QLineEdit(self.Frame)
        self.line_12FechaMes.setMaxLength(5)
        self.line_12FechaMes.setObjectName("line_12FechaMes")
        self.gridLayout_6.addWidget(self.line_12FechaMes, 2, 9, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.Frame)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.gridLayout_6.addWidget(self.label_80, 2, 8, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.Frame)
        self.label_68.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.gridLayout_6.addWidget(self.label_68, 3, 7, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.Frame)
        self.label_69.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.gridLayout_6.addWidget(self.label_69, 3, 9, 1, 1)
        self.check_01Verano = QtWidgets.QCheckBox(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_01Verano.setFont(font)
        self.check_01Verano.setObjectName("check_01Verano")
        self.gridLayout_6.addWidget(self.check_01Verano, 2, 11, 1, 1)
        self.label_153 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_153.setFont(font)
        self.label_153.setObjectName("label_153")
        self.gridLayout_6.addWidget(self.label_153, 3, 4, 1, 1)
        self.line_13Altitud = QtWidgets.QLineEdit(self.Frame)
        self.line_13Altitud.setMaxLength(5)
        self.line_13Altitud.setObjectName("line_13Altitud")
        self.gridLayout_6.addWidget(self.line_13Altitud, 3, 5, 1, 1)
        self.check_02TiempoReal = QtWidgets.QCheckBox(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.check_02TiempoReal.setFont(font)
        self.check_02TiempoReal.setObjectName("check_02TiempoReal")
        self.gridLayout_6.addWidget(self.check_02TiempoReal, 3, 11, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_6)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.label_54 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_54.sizePolicy().hasHeightForWidth())
        self.label_54.setSizePolicy(sizePolicy)
        self.label_54.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_9.addWidget(self.label_54)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(1)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_157 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.gridLayout_8.addWidget(self.label_157, 0, 0, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.Frame)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.gridLayout_8.addWidget(self.label_72, 1, 9, 1, 1)
        self.line_18HoraRealH = QtWidgets.QLineEdit(self.Frame)
        self.line_18HoraRealH.setMaxLength(5)
        self.line_18HoraRealH.setObjectName("line_18HoraRealH")
        self.gridLayout_8.addWidget(self.line_18HoraRealH, 0, 5, 1, 1)
        self.label_156 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_156.setFont(font)
        self.label_156.setObjectName("label_156")
        self.gridLayout_8.addWidget(self.label_156, 0, 4, 1, 1)
        self.line_16G = QtWidgets.QLineEdit(self.Frame)
        self.line_16G.setMaxLength(7)
        self.line_16G.setObjectName("line_16G")
        self.gridLayout_8.addWidget(self.line_16G, 0, 1, 1, 1)
        self.label_158 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_158.setFont(font)
        self.label_158.setObjectName("label_158")
        self.gridLayout_8.addWidget(self.label_158, 0, 2, 1, 1)
        self.line_17Dh = QtWidgets.QLineEdit(self.Frame)
        self.line_17Dh.setMaxLength(5)
        self.line_17Dh.setObjectName("line_17Dh")
        self.gridLayout_8.addWidget(self.line_17Dh, 0, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.Frame)
        self.label_70.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.gridLayout_8.addWidget(self.label_70, 1, 5, 1, 1)
        self.line_20HoraRealS = QtWidgets.QLineEdit(self.Frame)
        self.line_20HoraRealS.setMaxLength(5)
        self.line_20HoraRealS.setObjectName("line_20HoraRealS")
        self.gridLayout_8.addWidget(self.line_20HoraRealS, 0, 9, 1, 1)
        self.line_19HoraRealM = QtWidgets.QLineEdit(self.Frame)
        self.line_19HoraRealM.setMaxLength(5)
        self.line_19HoraRealM.setObjectName("line_19HoraRealM")
        self.gridLayout_8.addWidget(self.line_19HoraRealM, 0, 7, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.Frame)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.gridLayout_8.addWidget(self.label_81, 0, 6, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.Frame)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.gridLayout_8.addWidget(self.label_82, 0, 8, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.Frame)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.gridLayout_8.addWidget(self.label_71, 1, 7, 1, 1)
        self.pushButton_Calcular = QtWidgets.QPushButton(self.Frame)
        self.pushButton_Calcular.setObjectName("pushButton_Calcular")
        self.gridLayout_8.addWidget(self.pushButton_Calcular, 1, 1, 1, 2)
        self.verticalLayout_9.addLayout(self.gridLayout_8)
        self.label_55 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_55.sizePolicy().hasHeightForWidth())
        self.label_55.setSizePolicy(sizePolicy)
        self.label_55.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_9.addWidget(self.label_55)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_154 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.gridLayout_2.addWidget(self.label_154, 0, 0, 1, 1)
        self.line_23DhTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_23DhTiempoReal.setMaxLength(5)
        self.line_23DhTiempoReal.setObjectName("line_23DhTiempoReal")
        self.gridLayout_2.addWidget(self.line_23DhTiempoReal, 0, 5, 1, 1)
        self.label_159 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_159.setFont(font)
        self.label_159.setObjectName("label_159")
        self.gridLayout_2.addWidget(self.label_159, 0, 2, 1, 1)
        self.line_22GTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_22GTiempoReal.setMaxLength(7)
        self.line_22GTiempoReal.setObjectName("line_22GTiempoReal")
        self.gridLayout_2.addWidget(self.line_22GTiempoReal, 0, 3, 1, 1)
        self.line_21GhTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_21GhTiempoReal.setMaxLength(5)
        self.line_21GhTiempoReal.setObjectName("line_21GhTiempoReal")
        self.gridLayout_2.addWidget(self.line_21GhTiempoReal, 0, 1, 1, 1)
        self.label_160 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_160.setFont(font)
        self.label_160.setObjectName("label_160")
        self.gridLayout_2.addWidget(self.label_160, 0, 4, 1, 1)
        self.label_161 = QtWidgets.QLabel(self.Frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_161.setFont(font)
        self.label_161.setObjectName("label_161")
        self.gridLayout_2.addWidget(self.label_161, 0, 6, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.Frame)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.gridLayout_2.addWidget(self.label_83, 0, 8, 1, 1)
        self.line_25MinuTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_25MinuTiempoReal.setMaxLength(5)
        self.line_25MinuTiempoReal.setObjectName("line_25MinuTiempoReal")
        self.gridLayout_2.addWidget(self.line_25MinuTiempoReal, 0, 9, 1, 1)
        self.line_26SeguTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_26SeguTiempoReal.setMaxLength(5)
        self.line_26SeguTiempoReal.setObjectName("line_26SeguTiempoReal")
        self.gridLayout_2.addWidget(self.line_26SeguTiempoReal, 0, 11, 1, 1)
        self.line_24HoraTiempoReal = QtWidgets.QLineEdit(self.Frame)
        self.line_24HoraTiempoReal.setMaxLength(5)
        self.line_24HoraTiempoReal.setObjectName("line_24HoraTiempoReal")
        self.gridLayout_2.addWidget(self.line_24HoraTiempoReal, 0, 7, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.Frame)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.gridLayout_2.addWidget(self.label_84, 0, 10, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        self.layout_plot = QtWidgets.QVBoxLayout()
        self.layout_plot.setObjectName("layout_plot")
        self.verticalLayout_9.addLayout(self.layout_plot)
        self.label_59 = QtWidgets.QLabel(self.Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_59.sizePolicy().hasHeightForWidth())
        self.label_59.setSizePolicy(sizePolicy)
        self.label_59.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_59.setFont(font)
        self.label_59.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_9.addWidget(self.label_59)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuPotSolar = QtWidgets.QMenu(self.menubar)
        self.menuPotSolar.setObjectName("menuPotSolar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPotSolar.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_52.setText(_translate("mainWindow", "Datos generales"))
        self.line_09HoraESTM.setText(_translate("mainWindow", "16"))
        self.line_10HoraESTS.setText(_translate("mainWindow", "0"))
        self.label_77.setText(_translate("mainWindow", ":"))
        self.label_146.setText(_translate("mainWindow", "Latitud N (°):"))
        self.label_56.setText(_translate("mainWindow", "Longitud W (°):"))
        self.line_01Latitud.setText(_translate("mainWindow", "4.61"))
        self.line_08HoraESTH.setText(_translate("mainWindow", "13"))
        self.label_67.setText(_translate("mainWindow", "s"))
        self.label_66.setText(_translate("mainWindow", "min"))
        self.label_151.setText(_translate("mainWindow", "Hora EST (TL):"))
        self.label_148.setText(_translate("mainWindow", "Orientación  (°):"))
        self.label_79.setText(_translate("mainWindow", ":"))
        self.label_65.setText(_translate("mainWindow", "hr"))
        self.line_06Gh.setText(_translate("mainWindow", "800"))
        self.label_149.setText(_translate("mainWindow", "Gh*  (W/m^2):"))
        self.line_05Orientacion.setText(_translate("mainWindow", "0"))
        self.line_02Longitud.setText(_translate("mainWindow", "70.08"))
        self.label_147.setText(_translate("mainWindow", "Huso horario:"))
        self.label_57.setText(_translate("mainWindow", "Inclinación (°):"))
        self.line_03HusoHorario.setText(_translate("mainWindow", "-5"))
        self.line_04Inclinacion.setText(_translate("mainWindow", "6"))
        self.label_150.setText(_translate("mainWindow", "Albedo:"))
        self.line_07Albedo.setText(_translate("mainWindow", "0.3"))
        self.label_152.setText(_translate("mainWindow", "Fecha:"))
        self.line_11FechaDia.setText(_translate("mainWindow", "11"))
        self.line_12FechaMes.setText(_translate("mainWindow", "9"))
        self.label_80.setText(_translate("mainWindow", "-"))
        self.label_68.setText(_translate("mainWindow", "día"))
        self.label_69.setText(_translate("mainWindow", "mes"))
        self.check_01Verano.setText(_translate("mainWindow", "¿Verano?"))
        self.label_153.setText(_translate("mainWindow", "Altitud (km):"))
        self.line_13Altitud.setText(_translate("mainWindow", "2.6"))
        self.check_02TiempoReal.setText(_translate("mainWindow", "¿Tiempo real?"))
        self.label_54.setText(_translate("mainWindow", "Resultado calculado a partir del dato de radiación horizontal ingresado"))
        self.label_157.setText(_translate("mainWindow", "G(i,y)* (W/m^2):"))
        self.label_72.setText(_translate("mainWindow", "s"))
        self.line_18HoraRealH.setText(_translate("mainWindow", "0"))
        self.label_156.setText(_translate("mainWindow", "Tiempo solar verdadero:"))
        self.line_16G.setText(_translate("mainWindow", "0"))
        self.label_158.setText(_translate("mainWindow", "Dh* (W/m^2):"))
        self.line_17Dh.setText(_translate("mainWindow", "0"))
        self.label_70.setText(_translate("mainWindow", "hr"))
        self.line_20HoraRealS.setText(_translate("mainWindow", "0"))
        self.line_19HoraRealM.setText(_translate("mainWindow", "0"))
        self.label_81.setText(_translate("mainWindow", ":"))
        self.label_82.setText(_translate("mainWindow", ":"))
        self.label_71.setText(_translate("mainWindow", "min"))
        self.pushButton_Calcular.setText(_translate("mainWindow", "Calcular"))
        self.label_55.setText(_translate("mainWindow", "Resultado calculado en tiempo real"))
        self.label_154.setText(_translate("mainWindow", "Gh*  (W/m^2):"))
        self.line_23DhTiempoReal.setText(_translate("mainWindow", "0"))
        self.label_159.setText(_translate("mainWindow", "G(i,y)* (W/m^2):"))
        self.line_22GTiempoReal.setText(_translate("mainWindow", "0"))
        self.line_21GhTiempoReal.setText(_translate("mainWindow", "0"))
        self.label_160.setText(_translate("mainWindow", "Dh* (W/m^2):"))
        self.label_161.setText(_translate("mainWindow", "Hora de la última medida:"))
        self.label_83.setText(_translate("mainWindow", ":"))
        self.line_25MinuTiempoReal.setText(_translate("mainWindow", "0"))
        self.line_26SeguTiempoReal.setText(_translate("mainWindow", "0"))
        self.line_24HoraTiempoReal.setText(_translate("mainWindow", "0"))
        self.label_84.setText(_translate("mainWindow", ":"))
        self.label_59.setText(_translate("mainWindow", "Energías renovables - 2019_20 - Grupo 3: Alejandro Cárdenas, Daniel González, Erin Pinzón, Germán Sánchez"))
        self.menuPotSolar.setTitle(_translate("mainWindow", "Calculadora Potencia Solar"))

